spring.application.name=medsync
#configuration of the DB H2
spring.datasource.url=jdbc:h2:mem:medsyncdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#enable the console of H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
#show sql commands for the debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true